services:
  app_divo_simone:
    container_name: app_divo_simone
    build: .
    ports:
      - "5173:5173"
      - "3000:3000"

  mongo_divo_simone:
    container_name: mongo_divo_simone
    image: mongo:latest
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"